version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: PostgresDockerFile
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=${DbPass}"
